In [1]:
#Import the NUMPY package under the name np.

import numpy as np

In [2]:
#2. Print the NUMPY version and the configuration.
np.__version__


'1.16.2'

In [3]:
np.show_config()

mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/julieG/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/julieG/anaconda3/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/julieG/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/julieG/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/julieG/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/julieG/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/julieG/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/julieG/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/julieG/anaconda3/lib

In [50]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
a=np.random.rand(2,3,5)

In [51]:
#4. Print a.

print(a)

[[[0.19102683 0.44065892 0.45097982 0.16341091 0.39912228]
  [0.61734828 0.35778891 0.21110764 0.24826243 0.44358694]
  [0.62452849 0.55696916 0.22491614 0.02669724 0.09169204]]

 [[0.11570842 0.14735965 0.53119788 0.97002082 0.89205895]
  [0.3355214  0.25682355 0.47688291 0.09827139 0.89860608]
  [0.75631506 0.31176594 0.66367519 0.46553431 0.62876866]]]


In [52]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

b=np.ones((5,2,3))

In [53]:
#6. Print b.

print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [54]:
#7. Do a and b have the same size? How do you prove that in Python code?
print(a.size)

30


In [55]:
print(b.size)

30


In [56]:
#8. Are you able to add a and b? Why or why not?

np.concatenate((a,b))

#non, elles ne font pas la même dimension

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [57]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
   
c=np.transpose(b,(1,2,0))
print(c)






[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [93]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

d=np.add(a,c)

#les deux ont la même dimension maintenant

In [94]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

print(a)
print(d)

#c'est la somme des valeurs de a et c que l'on retrouve pour chaque valeur dans d

[[[0.19102683 0.44065892 0.45097982 0.16341091 0.39912228]
  [0.61734828 0.35778891 0.21110764 0.24826243 0.44358694]
  [0.62452849 0.55696916 0.22491614 0.02669724 0.09169204]]

 [[0.11570842 0.14735965 0.53119788 0.97002082 0.89205895]
  [0.3355214  0.25682355 0.47688291 0.09827139 0.89860608]
  [0.75631506 0.31176594 0.66367519 0.46553431 0.62876866]]]
[[[1.19102683 1.44065892 1.45097982 1.16341091 1.39912228]
  [1.61734828 1.35778891 1.21110764 1.24826243 1.44358694]
  [1.62452849 1.55696916 1.22491614 1.02669724 1.09169204]]

 [[1.11570842 1.14735965 1.53119788 1.97002082 1.89205895]
  [1.3355214  1.25682355 1.47688291 1.09827139 1.89860608]
  [1.75631506 1.31176594 1.66367519 1.46553431 1.62876866]]]


In [95]:
#12. Multiply a and c. Assign the result to e.

e=a*c

In [96]:
#13. Does e equal to a? Why or why not?

#Oui, toutes les valeurs de c sont égales à 1 donc quand on les multiplient avec les valeurs de a pour obtenir e ça ne change pas les valeurs (x*1 = x)

In [99]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

d_min=np.min(d)
print(d_min)
d_max=np.max(d)
print(d_max)
d_mean=np.mean(d)
print(d_mean)

1.0266972449349265
1.9700208213868233
1.4198868745302513


In [101]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

g=np.empty([2,3,5])

print(f)


[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [104]:
'''16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.'''

f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75
f[d==d_mean] = 50
f[(d==d_min)] = 0
f[(d==d_max)] = 100

print(f)


[[[ 25.  75.  75.  25.  25.]
  [ 75.  25.  25.  25.  75.]
  [ 75.  75.  25.   0.  25.]]

 [[ 25.  25.  75. 100.  75.]
  [ 25.  25.  75.  25.  75.]
  [ 75.  25.  75.  75.  75.]]]


In [105]:
"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""

print(d)
print(f)

[[[1.19102683 1.44065892 1.45097982 1.16341091 1.39912228]
  [1.61734828 1.35778891 1.21110764 1.24826243 1.44358694]
  [1.62452849 1.55696916 1.22491614 1.02669724 1.09169204]]

 [[1.11570842 1.14735965 1.53119788 1.97002082 1.89205895]
  [1.3355214  1.25682355 1.47688291 1.09827139 1.89860608]
  [1.75631506 1.31176594 1.66367519 1.46553431 1.62876866]]]
[[[ 25.  75.  75.  25.  25.]
  [ 75.  25.  25.  25.  75.]
  [ 75.  75.  25.   0.  25.]]

 [[ 25.  25.  75. 100.  75.]
  [ 25.  25.  75.  25.  75.]
  [ 75.  25.  75.  75.  75.]]]
