# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [15]:
import pandas as pd
import numpy as np

## Regression Model Evaluation

In [2]:
from sklearn.datasets import load_boston

data = load_boston()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=['MEDV'])

data = pd.concat([X, y], axis=1)

In [3]:
data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [4]:
from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(data, test_size=0.2)

## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [25]:
from sklearn.linear_model import LinearRegression

y_train = train_set['MEDV']
X_train = train_set.drop(columns = ['MEDV'])
model_1 = LinearRegression()
model_1.fit(X_train, y_train)
y_train_pred = model_1.predict(X_train)


array([-8.99908445e-02,  5.66613651e-02,  3.80752046e-02,  2.56776962e+00,
       -1.76273776e+01,  3.43536317e+00,  1.39145536e-02, -1.49341498e+00,
        2.92618621e-01, -1.23885385e-02, -9.64827579e-01,  1.14125328e-02,
       -5.91267781e-01])

In [22]:
y_test = test_set['MEDV']
X_test = test_set.drop(columns = ['MEDV'])
model_1.fit(X_test, y_test)
y_test_pred = model_1_test.predict(X_test)


## 3. Calculate and print R-squared for both the training and the testing set.

In [28]:
model_1.fit(X_train, y_train)
model_1.coef_
model_1.score(X_train, y_train)

0.7613553103341599

In [29]:
model_1.fit(X_test, y_test)
model_1.coef_
model_1.score(X_test, y_test)

0.7008080573040966

## 4. Calculate and print mean squared error for both the training and the testing set.

In [30]:
from sklearn.metrics import mean_squared_error

mean_squared_error(y_train, y_train_pred)

20.587234913028343

In [31]:
mean_squared_error(y_test, y_test_pred)

23.005230817071208

## 5. Calculate and print mean absolute error for both the training and the testing set.

In [32]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_train, y_train_pred)

3.1896709340156275

In [34]:
mean_absolute_error(y_test, y_test_pred)

3.5520532967511675

## Classification Model Evaluation

In [39]:
from sklearn.datasets import load_iris

data = load_iris()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=["class"])

data = pd.concat([X, y], axis=1)
data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   class  
0      0  
1      0  
2      0  
3      0  
4      0

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [36]:
from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(data, test_size=0.2)

## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [40]:
from sklearn.linear_model import LogisticRegression

y_train = train_set['class']
X_train = train_set.drop(columns = ['class'])
model_1 = LogisticRegression()
model_1.fit(X_train, y_train)
y_train_pred = model_1.predict(X_train)

/Users/julieG/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/julieG/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [42]:
y_test = test_set['class']
X_test = test_set.drop(columns = ['class'])
model_1.fit(X_test, y_test)
y_test_pred = model_1.predict(X_test)


/Users/julieG/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/julieG/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


## 8. Calculate and print the accuracy score for both the training and the testing set.

In [46]:
from sklearn.metrics import accuracy_score
accuracy_score(y_train, y_train_pred)

0.9666666666666667

In [44]:
accuracy_score(y_test, y_test_pred)

0.8333333333333334

## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [49]:
from sklearn.metrics import balanced_accuracy_score
balanced_accuracy_score(y_train, y_train_pred)

0.9674185463659147

In [50]:
balanced_accuracy_score(y_test, y_test_pred)

0.7916666666666666

## 10. Calculate and print the precision score for both the training and the testing set.

In [53]:
from sklearn.metrics import precision_score
precision_score(y_train, y_train_pred, average='micro') 

0.9666666666666667

In [54]:
precision_score(y_test, y_test_pred, average='micro') 

0.8333333333333334

## 11. Calculate and print the recall score for both the training and the testing set.

In [55]:
from sklearn.metrics import recall_score
recall_score(y_train, y_train_pred, average='micro')

0.9666666666666667

In [56]:
recall_score(y_test, y_test_pred, average='micro')

0.8333333333333334

## 12. Calculate and print the F1 score for both the training and the testing set.

In [57]:
from sklearn.metrics import f1_score
f1_score(y_train, y_train_pred, average='micro')

0.9666666666666667

In [58]:
f1_score(y_test, y_test_pred, average='micro')

0.8333333333333334

## 13. Generate confusion matrices for both the training and the testing set.

In [59]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_train, y_train_pred)

array([[40,  0,  0],
       [ 0, 39,  3],
       [ 0,  1, 37]])

In [60]:
confusion_matrix(y_test, y_test_pred)

array([[10,  0,  0],
       [ 0,  3,  5],
       [ 0,  0, 12]])

## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.